version: '3.8'
networks:
    ntwk:

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        volumes:
            - ./frontend:/app
        working_dir: /app
        networks:
            - ntwk

    keycloak:
        image: keycloak/keycloak
        container_name: keycloak
        command: start-dev --import-realm
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: dev-file
        ports:
            - 8080:8080
        volumes:
            - ./docker/keycloak/import:/opt/keycloak/data/import
        networks:
            - ntwk
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/master/protocol/openid-connect/certs"]
            interval: 30s
            timeout: 10s
            retries: 5